// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void scrSplashLoaded(lv_event_t * e);
void scrLoadStartAny(lv_event_t * e);
void scrLoadStartStandBy(lv_event_t * e);
void btnStartClick(lv_event_t * e);
void pnSB2SettingsClick(lv_event_t * e);
void scrMeasurmentsLoadStart(lv_event_t * e);
void pnClearClick(lv_event_t * e);
void pnStopClicked(lv_event_t * e);
void pnNextClick(lv_event_t * e);
void pnSettingSaveClick(lv_event_t * e);
void ddCalibrationChange(lv_event_t * e);
void ddSettingsTimesetChange(lv_event_t * e);
void btnCalEditClick(lv_event_t * e);
void pnWebSettingsClick(lv_event_t * e);
void pnCalibrationEditSaveClick(lv_event_t * e);
void pnCalibrationEditCancelClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
