// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#include "ui_custom.h"
#include "ui_functions.h"

void scrMeasurmentsLoadStart(lv_event_t * e)
{
	uiFillScreenMeasurements();
}

void scrLoadStartAny(lv_event_t * e)
{
	lv_obj_set_parent(ui_pnGlobals, e->target);
}

void scrLoadStartStandBy(lv_event_t * e)
{
	uiFillScreenStandBy();
}

void scrSplashLoaded(lv_event_t * e)
{
	lv_timer_create([](lv_timer_t * timer){
											lv_timer_del(timer);
											_ui_screen_change(&ui_StandBy, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_StandBy_screen_init);
											lv_timer_t * uiUpdateTimer = lv_timer_create(uiUpdateOnTimer, 100, NULL);
										}
	,1000, NULL);
}

void pnStopClicked(lv_event_t * e)
{
	uiStopMeasure();
}

void btnStartClick(lv_event_t * e)
{
	uiBeginMeasure();
}

void pnNextClick(lv_event_t * e)
{
	uiBeginMeasure();
}

void pnSB2SettingsClick(lv_event_t * e)
{
    uiEnterSettingsMenu();
}

void pnClearClick(lv_event_t * e)
{
	uiClearMeasurements();
}

void pnSettingSaveClick(lv_event_t * e)
{
	uiLeaveSettingsMenu();
}

void btnCalEditClick(lv_event_t * e)
{
	uiEnterCalibrationEdit();
}

void pnCalibrationEditSaveClick(lv_event_t * e)
{
	uiLeaveCalibrationEdit(true);
}

void pnCalibrationEditCancelClick(lv_event_t * e)
{
	uiLeaveCalibrationEdit(false);
}

void pnWebSettingsClick(lv_event_t * e)
{
	uiEnterWebSettings();
}

void ddCalibrationChange(lv_event_t * e)
{
	uiChangeCalibration();
}

void ddSettingsTimesetChange(lv_event_t * e)
{
	uiChangeTimeset();
}
