// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#include "../ui.h"

lv_obj_t * ui_CalibrationEdit = NULL;
lv_obj_t * ui_taName = NULL;
lv_obj_t * ui_sbFactorA = NULL;
lv_obj_t * ui_sbFactorB = NULL;
lv_obj_t * ui_pnCalEditSave = NULL;
lv_obj_t * ui_lbPnCalEditSave = NULL;
lv_obj_t * ui_pnCalEditCancel = NULL;
lv_obj_t * ui_lbPnCalEditCancel = NULL;
lv_obj_t * ui_btnFactorAPlus = NULL;
lv_obj_t * ui_lbBtnFactorAPlus = NULL;
lv_obj_t * ui_btnFactorBPlus = NULL;
lv_obj_t * ui_lbBtnFactorBPlus = NULL;
lv_obj_t * ui_btnFactorAMinus = NULL;
lv_obj_t * ui_lbBtnFactorAMinus = NULL;
lv_obj_t * ui_btnFactorBMinus = NULL;
lv_obj_t * ui_lbBtnFactorBMinus = NULL;
lv_obj_t * ui_kbKeyboard = NULL;
// event funtions
void ui_event_taName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_kbKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_kbKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pnCalEditSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnCalibrationEditSaveClick(e);
    }
}

void ui_event_pnCalEditCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnCalibrationEditCancelClick(e);
    }
}

void ui_event_btnFactorAPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_sbFactorA, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_sbFactorA, 1);
    }
}

void ui_event_btnFactorBPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_sbFactorB, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_sbFactorB, 1);
    }
}

void ui_event_btnFactorAMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_sbFactorA, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_sbFactorA, -1);
    }
}

void ui_event_btnFactorBMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_sbFactorB, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_sbFactorB, -1);
    }
}

// build funtions

void ui_CalibrationEdit_screen_init(void)
{
    ui_CalibrationEdit = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalibrationEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_taName = lv_textarea_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_taName, 200);
    lv_obj_set_height(ui_taName, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_taName, 0);
    lv_obj_set_y(ui_taName, -130);
    lv_obj_set_align(ui_taName, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_taName, 32);
    lv_textarea_set_placeholder_text(ui_taName, "Name");
    lv_textarea_set_one_line(ui_taName, true);

    ui_sbFactorA = lv_spinbox_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_sbFactorA, 200);
    lv_obj_set_height(ui_sbFactorA, 42);
    lv_obj_set_x(ui_sbFactorA, 0);
    lv_obj_set_y(ui_sbFactorA, -80);
    lv_obj_set_align(ui_sbFactorA, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_sbFactorA, 5, 1);
    lv_spinbox_set_range(ui_sbFactorA, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_sbFactorA, 1 - 1);

    ui_sbFactorB = lv_spinbox_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_sbFactorB, 200);
    lv_obj_set_height(ui_sbFactorB, 42);
    lv_obj_set_x(ui_sbFactorB, 0);
    lv_obj_set_y(ui_sbFactorB, -30);
    lv_obj_set_align(ui_sbFactorB, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_sbFactorB, 4, 2);
    lv_spinbox_set_range(ui_sbFactorB, -9999, 9999);
    lv_spinbox_set_cursor_pos(ui_sbFactorB, 1 - 1);

    ui_pnCalEditSave = lv_obj_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_pnCalEditSave, 307);
    lv_obj_set_height(ui_pnCalEditSave, 78);
    lv_obj_set_x(ui_pnCalEditSave, -160);
    lv_obj_set_y(ui_pnCalEditSave, 127);
    lv_obj_set_align(ui_pnCalEditSave, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnCalEditSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnCalEditSave, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnCalEditSave, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnCalEditSave = lv_label_create(ui_pnCalEditSave);
    lv_obj_set_width(ui_lbPnCalEditSave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnCalEditSave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnCalEditSave, 46);
    lv_obj_set_y(ui_lbPnCalEditSave, 0);
    lv_obj_set_align(ui_lbPnCalEditSave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnCalEditSave, "Save");
    lv_obj_set_style_text_font(ui_lbPnCalEditSave, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnCalEditCancel = lv_obj_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_pnCalEditCancel, 307);
    lv_obj_set_height(ui_pnCalEditCancel, 78);
    lv_obj_set_x(ui_pnCalEditCancel, 149);
    lv_obj_set_y(ui_pnCalEditCancel, 181);
    lv_obj_set_align(ui_pnCalEditCancel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnCalEditCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnCalEditCancel, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnCalEditCancel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnCalEditCancel = lv_label_create(ui_pnCalEditCancel);
    lv_obj_set_width(ui_lbPnCalEditCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnCalEditCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnCalEditCancel, -80);
    lv_obj_set_y(ui_lbPnCalEditCancel, 0);
    lv_obj_set_align(ui_lbPnCalEditCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnCalEditCancel, "Cancel");
    lv_obj_set_style_text_font(ui_lbPnCalEditCancel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnFactorAPlus = lv_btn_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_btnFactorAPlus, 40);
    lv_obj_set_height(ui_btnFactorAPlus, 39);
    lv_obj_set_x(ui_btnFactorAPlus, 130);
    lv_obj_set_y(ui_btnFactorAPlus, -80);
    lv_obj_set_align(ui_btnFactorAPlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFactorAPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFactorAPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnFactorAPlus, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_btnFactorAPlus, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_lbBtnFactorAPlus = lv_label_create(ui_btnFactorAPlus);
    lv_obj_set_width(ui_lbBtnFactorAPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnFactorAPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnFactorAPlus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnFactorAPlus, "+");
    lv_obj_set_style_text_font(ui_lbBtnFactorAPlus, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnFactorBPlus = lv_btn_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_btnFactorBPlus, 40);
    lv_obj_set_height(ui_btnFactorBPlus, 39);
    lv_obj_set_x(ui_btnFactorBPlus, 130);
    lv_obj_set_y(ui_btnFactorBPlus, -30);
    lv_obj_set_align(ui_btnFactorBPlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFactorBPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFactorBPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnFactorBPlus, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_btnFactorBPlus, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_lbBtnFactorBPlus = lv_label_create(ui_btnFactorBPlus);
    lv_obj_set_width(ui_lbBtnFactorBPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnFactorBPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnFactorBPlus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnFactorBPlus, "+");
    lv_obj_set_style_text_font(ui_lbBtnFactorBPlus, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnFactorAMinus = lv_btn_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_btnFactorAMinus, 40);
    lv_obj_set_height(ui_btnFactorAMinus, 39);
    lv_obj_set_x(ui_btnFactorAMinus, -130);
    lv_obj_set_y(ui_btnFactorAMinus, -80);
    lv_obj_set_align(ui_btnFactorAMinus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFactorAMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFactorAMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnFactorAMinus, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_btnFactorAMinus, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_lbBtnFactorAMinus = lv_label_create(ui_btnFactorAMinus);
    lv_obj_set_width(ui_lbBtnFactorAMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnFactorAMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnFactorAMinus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnFactorAMinus, "-");
    lv_obj_set_style_text_font(ui_lbBtnFactorAMinus, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnFactorBMinus = lv_btn_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_btnFactorBMinus, 40);
    lv_obj_set_height(ui_btnFactorBMinus, 39);
    lv_obj_set_x(ui_btnFactorBMinus, -130);
    lv_obj_set_y(ui_btnFactorBMinus, -30);
    lv_obj_set_align(ui_btnFactorBMinus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFactorBMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFactorBMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnFactorBMinus, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_btnFactorBMinus, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_lbBtnFactorBMinus = lv_label_create(ui_btnFactorBMinus);
    lv_obj_set_width(ui_lbBtnFactorBMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnFactorBMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnFactorBMinus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnFactorBMinus, "-");
    lv_obj_set_style_text_font(ui_lbBtnFactorBMinus, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kbKeyboard = lv_keyboard_create(ui_CalibrationEdit);
    lv_obj_set_width(ui_kbKeyboard, 400);
    lv_obj_set_height(ui_kbKeyboard, 120);
    lv_obj_set_x(ui_kbKeyboard, 0);
    lv_obj_set_y(ui_kbKeyboard, -40);
    lv_obj_set_align(ui_kbKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_kbKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_taName, ui_event_taName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnCalEditSave, ui_event_pnCalEditSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnCalEditCancel, ui_event_pnCalEditCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFactorAPlus, ui_event_btnFactorAPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFactorBPlus, ui_event_btnFactorBPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFactorAMinus, ui_event_btnFactorAMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFactorBMinus, ui_event_btnFactorBMinus, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_kbKeyboard, ui_taName);

}

void ui_CalibrationEdit_screen_destroy(void)
{
    if(ui_CalibrationEdit) lv_obj_del(ui_CalibrationEdit);

    // NULL screen variables
    ui_CalibrationEdit = NULL;
    ui_taName = NULL;
    ui_sbFactorA = NULL;
    ui_sbFactorB = NULL;
    ui_pnCalEditSave = NULL;
    ui_lbPnCalEditSave = NULL;
    ui_pnCalEditCancel = NULL;
    ui_lbPnCalEditCancel = NULL;
    ui_btnFactorAPlus = NULL;
    ui_lbBtnFactorAPlus = NULL;
    ui_btnFactorBPlus = NULL;
    ui_lbBtnFactorBPlus = NULL;
    ui_btnFactorAMinus = NULL;
    ui_lbBtnFactorAMinus = NULL;
    ui_btnFactorBMinus = NULL;
    ui_lbBtnFactorBMinus = NULL;
    ui_kbKeyboard = NULL;

}
