// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#ifndef UI_CALIBRATIONEDIT_H
#define UI_CALIBRATIONEDIT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalibrationEdit
extern void ui_CalibrationEdit_screen_init(void);
extern void ui_CalibrationEdit_screen_destroy(void);
extern lv_obj_t * ui_CalibrationEdit;
extern void ui_event_taName(lv_event_t * e);
extern lv_obj_t * ui_taName;
extern lv_obj_t * ui_sbFactorA;
extern lv_obj_t * ui_sbFactorB;
extern void ui_event_pnCalEditSave(lv_event_t * e);
extern lv_obj_t * ui_pnCalEditSave;
extern lv_obj_t * ui_lbPnCalEditSave;
extern void ui_event_pnCalEditCancel(lv_event_t * e);
extern lv_obj_t * ui_pnCalEditCancel;
extern lv_obj_t * ui_lbPnCalEditCancel;
extern void ui_event_btnFactorAPlus(lv_event_t * e);
extern lv_obj_t * ui_btnFactorAPlus;
extern lv_obj_t * ui_lbBtnFactorAPlus;
extern void ui_event_btnFactorBPlus(lv_event_t * e);
extern lv_obj_t * ui_btnFactorBPlus;
extern lv_obj_t * ui_lbBtnFactorBPlus;
extern void ui_event_btnFactorAMinus(lv_event_t * e);
extern lv_obj_t * ui_btnFactorAMinus;
extern lv_obj_t * ui_lbBtnFactorAMinus;
extern void ui_event_btnFactorBMinus(lv_event_t * e);
extern lv_obj_t * ui_btnFactorBMinus;
extern lv_obj_t * ui_lbBtnFactorBMinus;
extern lv_obj_t * ui_kbKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

