// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#ifndef UI_MEASURMENTS_H
#define UI_MEASURMENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Measurments
extern void ui_Measurments_screen_init(void);
extern void ui_Measurments_screen_destroy(void);
extern void ui_event_Measurments(lv_event_t * e);
extern lv_obj_t * ui_Measurments;
extern void ui_event_pnMS2Main(lv_event_t * e);
extern lv_obj_t * ui_pnMS2Main;
extern lv_obj_t * ui_lbPnMS2Main;
extern void ui_event_pnClear(lv_event_t * e);
extern lv_obj_t * ui_pnClear;
extern lv_obj_t * ui_lbPnClear;
extern lv_obj_t * ui_lbRsd;
extern lv_obj_t * ui_lbRsdValue;
extern lv_obj_t * ui_lbAvgAsh;
extern lv_obj_t * ui_lbAvgAshValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

