// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#include "../ui.h"

lv_obj_t * ui_MeasureProgress = NULL;
lv_obj_t * ui_lbMeasurementRemaingTime = NULL;
lv_obj_t * ui_pnStop = NULL;
lv_obj_t * ui_lbPnStop = NULL;
lv_obj_t * ui_lbAvgCPS = NULL;
lv_obj_t * ui_lbMeasurementAsh = NULL;
lv_obj_t * ui_lbCPSrsd = NULL;
lv_obj_t * ui_lbMeasurementCount = NULL;
lv_obj_t * ui_lbAvgCPSvalue = NULL;
lv_obj_t * ui_lbCPSrsdValue = NULL;
lv_obj_t * ui_lbMeasurementAshValue = NULL;
lv_obj_t * ui_lbMeasurementCountValue = NULL;
lv_obj_t * ui_pnNext = NULL;
lv_obj_t * ui_lbPnNext = NULL;
lv_obj_t * ui_pnMP2Measurements = NULL;
lv_obj_t * ui_lbPnMP2Measurements = NULL;
// event funtions
void ui_event_MeasureProgress(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        scrLoadStartAny(e);
    }
}

void ui_event_pnStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnStopClicked(e);
    }
}

void ui_event_pnNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnNextClick(e);
    }
}

void ui_event_pnMP2Measurements(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Measurments, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Measurments_screen_init);
    }
}

// build funtions

void ui_MeasureProgress_screen_init(void)
{
    ui_MeasureProgress = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MeasureProgress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbMeasurementRemaingTime = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbMeasurementRemaingTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMeasurementRemaingTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMeasurementRemaingTime, 0);
    lv_obj_set_y(ui_lbMeasurementRemaingTime, -30);
    lv_obj_set_align(ui_lbMeasurementRemaingTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMeasurementRemaingTime, "120");
    lv_obj_set_style_text_font(ui_lbMeasurementRemaingTime, &ui_font_fntDigital64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnStop = lv_obj_create(ui_MeasureProgress);
    lv_obj_set_width(ui_pnStop, 307);
    lv_obj_set_height(ui_pnStop, 78);
    lv_obj_set_x(ui_pnStop, -160);
    lv_obj_set_y(ui_pnStop, 127);
    lv_obj_set_align(ui_pnStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnStop, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnStop, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnStop, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnStop = lv_label_create(ui_pnStop);
    lv_obj_set_width(ui_lbPnStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnStop, 46);
    lv_obj_set_y(ui_lbPnStop, 0);
    lv_obj_set_align(ui_lbPnStop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnStop, "Stop");
    lv_obj_set_style_text_font(ui_lbPnStop, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbAvgCPS = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbAvgCPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbAvgCPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbAvgCPS, -120);
    lv_obj_set_y(ui_lbAvgCPS, 25);
    lv_obj_set_align(ui_lbAvgCPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbAvgCPS, "Avg CPS:");

    ui_lbMeasurementAsh = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbMeasurementAsh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMeasurementAsh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMeasurementAsh, -103);
    lv_obj_set_y(ui_lbMeasurementAsh, 50);
    lv_obj_set_align(ui_lbMeasurementAsh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMeasurementAsh, "Ash:");
    lv_obj_add_flag(ui_lbMeasurementAsh, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_lbCPSrsd = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbCPSrsd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbCPSrsd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbCPSrsd, 100);
    lv_obj_set_y(ui_lbCPSrsd, 25);
    lv_obj_set_align(ui_lbCPSrsd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbCPSrsd, "CPS Rsd:");

    ui_lbMeasurementCount = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbMeasurementCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMeasurementCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMeasurementCount, 112);
    lv_obj_set_y(ui_lbMeasurementCount, 50);
    lv_obj_set_align(ui_lbMeasurementCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMeasurementCount, "Msr#:");
    lv_obj_add_flag(ui_lbMeasurementCount, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_lbAvgCPSvalue = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbAvgCPSvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbAvgCPSvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbAvgCPSvalue, -60);
    lv_obj_set_y(ui_lbAvgCPSvalue, 25);
    lv_obj_set_align(ui_lbAvgCPSvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbAvgCPSvalue, "200.57");

    ui_lbCPSrsdValue = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbCPSrsdValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbCPSrsdValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbCPSrsdValue, 155);
    lv_obj_set_y(ui_lbCPSrsdValue, 25);
    lv_obj_set_align(ui_lbCPSrsdValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbCPSrsdValue, "0.6%");

    ui_lbMeasurementAshValue = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbMeasurementAshValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMeasurementAshValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMeasurementAshValue, -50);
    lv_obj_set_y(ui_lbMeasurementAshValue, 50);
    lv_obj_set_align(ui_lbMeasurementAshValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMeasurementAshValue, "11.6 %Ad");
    lv_obj_add_flag(ui_lbMeasurementAshValue, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_lbMeasurementCountValue = lv_label_create(ui_MeasureProgress);
    lv_obj_set_width(ui_lbMeasurementCountValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMeasurementCountValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMeasurementCountValue, 155);
    lv_obj_set_y(ui_lbMeasurementCountValue, 50);
    lv_obj_set_align(ui_lbMeasurementCountValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMeasurementCountValue, "11/12");
    lv_obj_add_flag(ui_lbMeasurementCountValue, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_pnNext = lv_obj_create(ui_MeasureProgress);
    lv_obj_set_width(ui_pnNext, 307);
    lv_obj_set_height(ui_pnNext, 78);
    lv_obj_set_x(ui_pnNext, -160);
    lv_obj_set_y(ui_pnNext, 127);
    lv_obj_set_align(ui_pnNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnNext, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnNext, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnNext, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnNext = lv_label_create(ui_pnNext);
    lv_obj_set_width(ui_lbPnNext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnNext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnNext, 46);
    lv_obj_set_y(ui_lbPnNext, 0);
    lv_obj_set_align(ui_lbPnNext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnNext, "Next");
    lv_obj_set_style_text_font(ui_lbPnNext, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnMP2Measurements = lv_obj_create(ui_MeasureProgress);
    lv_obj_set_width(ui_pnMP2Measurements, 307);
    lv_obj_set_height(ui_pnMP2Measurements, 78);
    lv_obj_set_x(ui_pnMP2Measurements, 149);
    lv_obj_set_y(ui_pnMP2Measurements, 181);
    lv_obj_set_align(ui_pnMP2Measurements, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnMP2Measurements, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnMP2Measurements, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnMP2Measurements, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnMP2Measurements, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnMP2Measurements = lv_label_create(ui_pnMP2Measurements);
    lv_obj_set_width(ui_lbPnMP2Measurements, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnMP2Measurements, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnMP2Measurements, -80);
    lv_obj_set_y(ui_lbPnMP2Measurements, 0);
    lv_obj_set_align(ui_lbPnMP2Measurements, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnMP2Measurements, "Measurements");
    lv_obj_set_style_text_font(ui_lbPnMP2Measurements, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_pnStop, ui_event_pnStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnNext, ui_event_pnNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnMP2Measurements, ui_event_pnMP2Measurements, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MeasureProgress, ui_event_MeasureProgress, LV_EVENT_ALL, NULL);

}

void ui_MeasureProgress_screen_destroy(void)
{
    if(ui_MeasureProgress) lv_obj_del(ui_MeasureProgress);

    // NULL screen variables
    ui_MeasureProgress = NULL;
    ui_lbMeasurementRemaingTime = NULL;
    ui_pnStop = NULL;
    ui_lbPnStop = NULL;
    ui_lbAvgCPS = NULL;
    ui_lbMeasurementAsh = NULL;
    ui_lbCPSrsd = NULL;
    ui_lbMeasurementCount = NULL;
    ui_lbAvgCPSvalue = NULL;
    ui_lbCPSrsdValue = NULL;
    ui_lbMeasurementAshValue = NULL;
    ui_lbMeasurementCountValue = NULL;
    ui_pnNext = NULL;
    ui_lbPnNext = NULL;
    ui_pnMP2Measurements = NULL;
    ui_lbPnMP2Measurements = NULL;

}
