// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#include "../ui.h"

lv_obj_t * ui_Measurments = NULL;
lv_obj_t * ui_pnMS2Main = NULL;
lv_obj_t * ui_lbPnMS2Main = NULL;
lv_obj_t * ui_pnClear = NULL;
lv_obj_t * ui_lbPnClear = NULL;
lv_obj_t * ui_lbRsd = NULL;
lv_obj_t * ui_lbRsdValue = NULL;
lv_obj_t * ui_lbAvgAsh = NULL;
lv_obj_t * ui_lbAvgAshValue = NULL;
// event funtions
void ui_event_Measurments(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        scrMeasurmentsLoadStart(e);
        scrLoadStartAny(e);
    }
}

void ui_event_pnMS2Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StandBy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_StandBy_screen_init);
    }
}

void ui_event_pnClear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnClearClick(e);
    }
}

// build funtions

void ui_Measurments_screen_init(void)
{
    ui_Measurments = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Measurments, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnMS2Main = lv_obj_create(ui_Measurments);
    lv_obj_set_width(ui_pnMS2Main, 307);
    lv_obj_set_height(ui_pnMS2Main, 78);
    lv_obj_set_x(ui_pnMS2Main, -160);
    lv_obj_set_y(ui_pnMS2Main, 127);
    lv_obj_set_align(ui_pnMS2Main, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnMS2Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnMS2Main, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnMS2Main, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnMS2Main = lv_label_create(ui_pnMS2Main);
    lv_obj_set_width(ui_lbPnMS2Main, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnMS2Main, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnMS2Main, 46);
    lv_obj_set_y(ui_lbPnMS2Main, 0);
    lv_obj_set_align(ui_lbPnMS2Main, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnMS2Main, "Main");
    lv_obj_set_style_text_font(ui_lbPnMS2Main, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnClear = lv_obj_create(ui_Measurments);
    lv_obj_set_width(ui_pnClear, 307);
    lv_obj_set_height(ui_pnClear, 78);
    lv_obj_set_x(ui_pnClear, 149);
    lv_obj_set_y(ui_pnClear, 181);
    lv_obj_set_align(ui_pnClear, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnClear, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnClear, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnClear = lv_label_create(ui_pnClear);
    lv_obj_set_width(ui_lbPnClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnClear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnClear, -80);
    lv_obj_set_y(ui_lbPnClear, 0);
    lv_obj_set_align(ui_lbPnClear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnClear, "Clear");
    lv_obj_set_style_text_font(ui_lbPnClear, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbRsd = lv_label_create(ui_Measurments);
    lv_obj_set_width(ui_lbRsd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbRsd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbRsd, 140);
    lv_obj_set_y(ui_lbRsd, 100);
    lv_obj_set_align(ui_lbRsd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbRsd, "Rsd:");

    ui_lbRsdValue = lv_label_create(ui_Measurments);
    lv_obj_set_width(ui_lbRsdValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbRsdValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbRsdValue, 180);
    lv_obj_set_y(ui_lbRsdValue, 100);
    lv_obj_set_align(ui_lbRsdValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbRsdValue, "1.113%");

    ui_lbAvgAsh = lv_label_create(ui_Measurments);
    lv_obj_set_width(ui_lbAvgAsh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbAvgAsh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbAvgAsh, 30);
    lv_obj_set_y(ui_lbAvgAsh, 100);
    lv_obj_set_align(ui_lbAvgAsh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbAvgAsh, "Avg Ash:");

    ui_lbAvgAshValue = lv_label_create(ui_Measurments);
    lv_obj_set_width(ui_lbAvgAshValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbAvgAshValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbAvgAshValue, 90);
    lv_obj_set_y(ui_lbAvgAshValue, 100);
    lv_obj_set_align(ui_lbAvgAshValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbAvgAshValue, "30.57%");

    lv_obj_add_event_cb(ui_pnMS2Main, ui_event_pnMS2Main, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnClear, ui_event_pnClear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Measurments, ui_event_Measurments, LV_EVENT_ALL, NULL);

}

void ui_Measurments_screen_destroy(void)
{
    if(ui_Measurments) lv_obj_del(ui_Measurments);

    // NULL screen variables
    ui_Measurments = NULL;
    ui_pnMS2Main = NULL;
    ui_lbPnMS2Main = NULL;
    ui_pnClear = NULL;
    ui_lbPnClear = NULL;
    ui_lbRsd = NULL;
    ui_lbRsdValue = NULL;
    ui_lbAvgAsh = NULL;
    ui_lbAvgAshValue = NULL;

}
