// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#ifndef UI_MEASUREPROGRESS_H
#define UI_MEASUREPROGRESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MeasureProgress
extern void ui_MeasureProgress_screen_init(void);
extern void ui_MeasureProgress_screen_destroy(void);
extern void ui_event_MeasureProgress(lv_event_t * e);
extern lv_obj_t * ui_MeasureProgress;
extern lv_obj_t * ui_lbMeasurementRemaingTime;
extern void ui_event_pnStop(lv_event_t * e);
extern lv_obj_t * ui_pnStop;
extern lv_obj_t * ui_lbPnStop;
extern lv_obj_t * ui_lbAvgCPS;
extern lv_obj_t * ui_lbMeasurementAsh;
extern lv_obj_t * ui_lbCPSrsd;
extern lv_obj_t * ui_lbMeasurementCount;
extern lv_obj_t * ui_lbAvgCPSvalue;
extern lv_obj_t * ui_lbCPSrsdValue;
extern lv_obj_t * ui_lbMeasurementAshValue;
extern lv_obj_t * ui_lbMeasurementCountValue;
extern void ui_event_pnNext(lv_event_t * e);
extern lv_obj_t * ui_pnNext;
extern lv_obj_t * ui_lbPnNext;
extern void ui_event_pnMP2Measurements(lv_event_t * e);
extern lv_obj_t * ui_pnMP2Measurements;
extern lv_obj_t * ui_lbPnMP2Measurements;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

