// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#include "../ui.h"

lv_obj_t * ui_StandBy = NULL;
lv_obj_t * ui_chtCpsHistory = NULL;
lv_obj_t * ui_btnStart = NULL;
lv_obj_t * ui_lbBtnStart = NULL;
lv_obj_t * ui_lbCurrentCPSval = NULL;
lv_obj_t * ui_lbCPSlabel = NULL;
lv_obj_t * ui_pnGlobals = NULL;
lv_obj_t * ui_lbClock = NULL;
lv_obj_t * ui_lbDate = NULL;
lv_obj_t * ui_imgBattery = NULL;
lv_obj_t * ui_pnSB2Measurements = NULL;
lv_obj_t * ui_lbPnSB2Measurements = NULL;
lv_obj_t * ui_pnSB2Settings = NULL;
lv_obj_t * ui_lbPnSB2Settings = NULL;
lv_obj_t * ui_lbCal = NULL;
lv_obj_t * ui_lbCalName = NULL;
lv_obj_t * ui_lbFactorA = NULL;
lv_obj_t * ui_lbFactorAvalue = NULL;
lv_obj_t * ui_lbFactorB = NULL;
lv_obj_t * ui_lbFactorBvalue = NULL;
lv_obj_t * ui_lbTime = NULL;
lv_obj_t * ui_lbTimeValue = NULL;
// event funtions
void ui_event_StandBy(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        scrLoadStartAny(e);
        scrLoadStartStandBy(e);
    }
}

void ui_event_btnStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnStartClick(e);
    }
}

void ui_event_pnSB2Measurements(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Measurments, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Measurments_screen_init);
    }
}

void ui_event_pnSB2Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnSB2SettingsClick(e);
    }
}

// build funtions

void ui_StandBy_screen_init(void)
{
    ui_StandBy = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StandBy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chtCpsHistory = lv_chart_create(ui_StandBy);
    lv_obj_set_width(ui_chtCpsHistory, 200);
    lv_obj_set_height(ui_chtCpsHistory, 140);
    lv_obj_set_x(ui_chtCpsHistory, -70);
    lv_obj_set_y(ui_chtCpsHistory, -20);
    lv_obj_set_align(ui_chtCpsHistory, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_chtCpsHistory, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_chtCpsHistory, LV_CHART_AXIS_PRIMARY_Y, 0, 400);
    lv_chart_set_range(ui_chtCpsHistory, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_axis_tick(ui_chtCpsHistory, LV_CHART_AXIS_PRIMARY_X, 10, 0, 10, 2, false, 50);
    lv_chart_set_axis_tick(ui_chtCpsHistory, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_chtCpsHistory, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_chtCpsHistory_series_1 = lv_chart_add_series(ui_chtCpsHistory, lv_color_hex(0x808080),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_chtCpsHistory_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_chtCpsHistory, ui_chtCpsHistory_series_1, ui_chtCpsHistory_series_1_array);

    ui_btnStart = lv_btn_create(ui_StandBy);
    lv_obj_set_width(ui_btnStart, 125);
    lv_obj_set_height(ui_btnStart, 39);
    lv_obj_set_x(ui_btnStart, 133);
    lv_obj_set_y(ui_btnStart, 22);
    lv_obj_set_align(ui_btnStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnStart, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_btnStart, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_lbBtnStart = lv_label_create(ui_btnStart);
    lv_obj_set_width(ui_lbBtnStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnStart, "Start");
    lv_obj_set_style_text_font(ui_lbBtnStart, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbCurrentCPSval = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbCurrentCPSval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbCurrentCPSval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbCurrentCPSval, 132);
    lv_obj_set_y(ui_lbCurrentCPSval, -55);
    lv_obj_set_align(ui_lbCurrentCPSval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbCurrentCPSval, "200");
    lv_obj_set_style_text_font(ui_lbCurrentCPSval, &ui_font_fntDigital64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbCPSlabel = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbCPSlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbCPSlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbCPSlabel, 132);
    lv_obj_set_y(ui_lbCPSlabel, -18);
    lv_obj_set_align(ui_lbCPSlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbCPSlabel, "cps");
    lv_obj_set_style_text_font(ui_lbCPSlabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnGlobals = lv_obj_create(ui_StandBy);
    lv_obj_set_width(ui_pnGlobals, 506);
    lv_obj_set_height(ui_pnGlobals, 98);
    lv_obj_set_x(ui_pnGlobals, 157);
    lv_obj_set_y(ui_pnGlobals, -166);
    lv_obj_set_align(ui_pnGlobals, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnGlobals, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnGlobals, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnGlobals, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbClock = lv_label_create(ui_pnGlobals);
    lv_obj_set_width(ui_lbClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbClock, -144);
    lv_obj_set_y(ui_lbClock, -4);
    lv_obj_set_align(ui_lbClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbClock, "20:00");
    lv_obj_set_style_text_font(ui_lbClock, &ui_font_fntSamsungSharpSans72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbDate = lv_label_create(ui_pnGlobals);
    lv_obj_set_width(ui_lbDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbDate, -143);
    lv_obj_set_y(ui_lbDate, 37);
    lv_obj_set_align(ui_lbDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbDate, "01.01.2025");
    lv_obj_set_style_text_font(ui_lbDate, &ui_font_fntSamsungSharpSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBattery = lv_img_create(ui_pnGlobals);
    lv_img_set_src(ui_imgBattery, &ui_img_battery_icons_png);
    lv_obj_set_width(ui_imgBattery, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_imgBattery, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_imgBattery, 20);
    lv_obj_set_y(ui_imgBattery, 36);
    lv_obj_set_align(ui_imgBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_min_width(ui_imgBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_imgBattery, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_imgBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_imgBattery, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnSB2Measurements = lv_obj_create(ui_StandBy);
    lv_obj_set_width(ui_pnSB2Measurements, 307);
    lv_obj_set_height(ui_pnSB2Measurements, 78);
    lv_obj_set_x(ui_pnSB2Measurements, -160);
    lv_obj_set_y(ui_pnSB2Measurements, 127);
    lv_obj_set_align(ui_pnSB2Measurements, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnSB2Measurements, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnSB2Measurements, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnSB2Measurements, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnSB2Measurements = lv_label_create(ui_pnSB2Measurements);
    lv_obj_set_width(ui_lbPnSB2Measurements, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnSB2Measurements, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnSB2Measurements, 46);
    lv_obj_set_y(ui_lbPnSB2Measurements, 0);
    lv_obj_set_align(ui_lbPnSB2Measurements, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnSB2Measurements, "Measurements");
    lv_obj_set_style_text_font(ui_lbPnSB2Measurements, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnSB2Settings = lv_obj_create(ui_StandBy);
    lv_obj_set_width(ui_pnSB2Settings, 307);
    lv_obj_set_height(ui_pnSB2Settings, 78);
    lv_obj_set_x(ui_pnSB2Settings, 149);
    lv_obj_set_y(ui_pnSB2Settings, 181);
    lv_obj_set_align(ui_pnSB2Settings, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnSB2Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnSB2Settings, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnSB2Settings, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnSB2Settings = lv_label_create(ui_pnSB2Settings);
    lv_obj_set_width(ui_lbPnSB2Settings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnSB2Settings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnSB2Settings, -80);
    lv_obj_set_y(ui_lbPnSB2Settings, 0);
    lv_obj_set_align(ui_lbPnSB2Settings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnSB2Settings, "Settings");
    lv_obj_set_style_text_font(ui_lbPnSB2Settings, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbCal = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbCal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbCal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbCal, 59);
    lv_obj_set_y(ui_lbCal, 65);
    lv_obj_set_align(ui_lbCal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbCal, "Cal:");

    ui_lbCalName = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbCalName, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbCalName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbCalName, 117);
    lv_obj_set_y(ui_lbCalName, 65);
    lv_obj_set_align(ui_lbCalName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbCalName, "Calibration1");

    ui_lbFactorA = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbFactorA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbFactorA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbFactorA, 65);
    lv_obj_set_y(ui_lbFactorA, 85);
    lv_obj_set_align(ui_lbFactorA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbFactorA, "A:");

    ui_lbFactorAvalue = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbFactorAvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbFactorAvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbFactorAvalue, 90);
    lv_obj_set_y(ui_lbFactorAvalue, 85);
    lv_obj_set_align(ui_lbFactorAvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbFactorAvalue, "0.16");

    ui_lbFactorB = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbFactorB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbFactorB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbFactorB, 132);
    lv_obj_set_y(ui_lbFactorB, 85);
    lv_obj_set_align(ui_lbFactorB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbFactorB, "B:");

    ui_lbFactorBvalue = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbFactorBvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbFactorBvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbFactorBvalue, 158);
    lv_obj_set_y(ui_lbFactorBvalue, 85);
    lv_obj_set_align(ui_lbFactorBvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbFactorBvalue, "-2.5");

    ui_lbTime = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTime, 52);
    lv_obj_set_y(ui_lbTime, 104);
    lv_obj_set_align(ui_lbTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbTime, "Time:");

    ui_lbTimeValue = lv_label_create(ui_StandBy);
    lv_obj_set_width(ui_lbTimeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTimeValue, 86);
    lv_obj_set_y(ui_lbTimeValue, 104);
    lv_obj_set_align(ui_lbTimeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbTimeValue, "60");

    lv_obj_add_event_cb(ui_btnStart, ui_event_btnStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnSB2Measurements, ui_event_pnSB2Measurements, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnSB2Settings, ui_event_pnSB2Settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StandBy, ui_event_StandBy, LV_EVENT_ALL, NULL);

}

void ui_StandBy_screen_destroy(void)
{
    if(ui_StandBy) lv_obj_del(ui_StandBy);

    // NULL screen variables
    ui_StandBy = NULL;
    ui_chtCpsHistory = NULL;
    ui_btnStart = NULL;
    ui_lbBtnStart = NULL;
    ui_lbCurrentCPSval = NULL;
    ui_lbCPSlabel = NULL;
    ui_pnGlobals = NULL;
    ui_lbClock = NULL;
    ui_lbDate = NULL;
    ui_imgBattery = NULL;
    ui_pnSB2Measurements = NULL;
    ui_lbPnSB2Measurements = NULL;
    ui_pnSB2Settings = NULL;
    ui_lbPnSB2Settings = NULL;
    ui_lbCal = NULL;
    ui_lbCalName = NULL;
    ui_lbFactorA = NULL;
    ui_lbFactorAvalue = NULL;
    ui_lbFactorB = NULL;
    ui_lbFactorBvalue = NULL;
    ui_lbTime = NULL;
    ui_lbTimeValue = NULL;

}
