// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#ifndef UI_STANDBY_H
#define UI_STANDBY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StandBy
extern void ui_StandBy_screen_init(void);
extern void ui_StandBy_screen_destroy(void);
extern void ui_event_StandBy(lv_event_t * e);
extern lv_obj_t * ui_StandBy;
extern lv_obj_t * ui_chtCpsHistory;
extern void ui_event_btnStart(lv_event_t * e);
extern lv_obj_t * ui_btnStart;
extern lv_obj_t * ui_lbBtnStart;
extern lv_obj_t * ui_lbCurrentCPSval;
extern lv_obj_t * ui_lbCPSlabel;
extern lv_obj_t * ui_pnGlobals;
extern lv_obj_t * ui_lbClock;
extern lv_obj_t * ui_lbDate;
extern lv_obj_t * ui_imgBattery;
extern void ui_event_pnSB2Measurements(lv_event_t * e);
extern lv_obj_t * ui_pnSB2Measurements;
extern lv_obj_t * ui_lbPnSB2Measurements;
extern void ui_event_pnSB2Settings(lv_event_t * e);
extern lv_obj_t * ui_pnSB2Settings;
extern lv_obj_t * ui_lbPnSB2Settings;
extern lv_obj_t * ui_lbCal;
extern lv_obj_t * ui_lbCalName;
extern lv_obj_t * ui_lbFactorA;
extern lv_obj_t * ui_lbFactorAvalue;
extern lv_obj_t * ui_lbFactorB;
extern lv_obj_t * ui_lbFactorBvalue;
extern lv_obj_t * ui_lbTime;
extern lv_obj_t * ui_lbTimeValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

