// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#include "../ui.h"

lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_imgZolarLogo = NULL;
// event funtions
void ui_event_Splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        scrSplashLoaded(e);
    }
}

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgZolarLogo = lv_img_create(ui_Splash);
    lv_img_set_src(ui_imgZolarLogo, &ui_img_zolar_logo_png);
    lv_obj_set_width(ui_imgZolarLogo, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_imgZolarLogo, LV_SIZE_CONTENT);    /// 287
    lv_obj_set_x(ui_imgZolarLogo, 12);
    lv_obj_set_y(ui_imgZolarLogo, -28);
    lv_obj_set_align(ui_imgZolarLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgZolarLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgZolarLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    ui_imgZolarLogo = NULL;

}
