// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#include "../ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_pnSettingsSave = NULL;
lv_obj_t * ui_lbPnSettingsSave = NULL;
lv_obj_t * ui_lbSettingsCal = NULL;
lv_obj_t * ui_lbSettingsTimeset = NULL;
lv_obj_t * ui_ddSettingsCalibration = NULL;
lv_obj_t * ui_ddSettingsTimeset = NULL;
lv_obj_t * ui_btnSettingsCalEdit = NULL;
lv_obj_t * ui_lbBtnSettingsCalEdit = NULL;
lv_obj_t * ui_pnSettingsWeb = NULL;
lv_obj_t * ui_lbPnSettingsWeb = NULL;
lv_obj_t * ui_pnSettingsOthers = NULL;
lv_obj_t * ui_Settings_Slider1 = NULL;
lv_obj_t * ui_lbSettingsBrightness = NULL;
lv_obj_t * ui_lbSettingsBrightness1 = NULL;
lv_obj_t * ui_swSettingsDarkTheme = NULL;
lv_obj_t * ui_lbSettingsBuzzer = NULL;
lv_obj_t * ui_swSettingsDarkTheme1 = NULL;
lv_obj_t * ui_ddSettingsLanguage = NULL;
lv_obj_t * ui_lbSettingsBrightness3 = NULL;
// event funtions
void ui_event_pnSettingsSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnSettingSaveClick(e);
    }
}

void ui_event_ddSettingsCalibration(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ddCalibrationChange(e);
    }
}

void ui_event_ddSettingsTimeset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ddSettingsTimesetChange(e);
    }
}

void ui_event_btnSettingsCalEdit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnCalEditClick(e);
    }
}

void ui_event_pnSettingsWeb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pnWebSettingsClick(e);
    }
}

void ui_event_swSettingsDarkTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DEFAULT);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnSettingsSave = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_pnSettingsSave, 307);
    lv_obj_set_height(ui_pnSettingsSave, 78);
    lv_obj_set_x(ui_pnSettingsSave, -160);
    lv_obj_set_y(ui_pnSettingsSave, 127);
    lv_obj_set_align(ui_pnSettingsSave, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnSettingsSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnSettingsSave, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnSettingsSave, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnSettingsSave = lv_label_create(ui_pnSettingsSave);
    lv_obj_set_width(ui_lbPnSettingsSave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnSettingsSave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnSettingsSave, 46);
    lv_obj_set_y(ui_lbPnSettingsSave, 0);
    lv_obj_set_align(ui_lbPnSettingsSave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnSettingsSave, "Save");
    lv_obj_set_style_text_font(ui_lbPnSettingsSave, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSettingsCal = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_lbSettingsCal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingsCal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSettingsCal, 93);
    lv_obj_set_y(ui_lbSettingsCal, -124);
    lv_obj_set_align(ui_lbSettingsCal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbSettingsCal, "Cal:");

    ui_lbSettingsTimeset = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_lbSettingsTimeset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingsTimeset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSettingsTimeset, 58);
    lv_obj_set_y(ui_lbSettingsTimeset, -76);
    lv_obj_set_align(ui_lbSettingsTimeset, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbSettingsTimeset, "Timeset:");

    ui_ddSettingsCalibration = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_ddSettingsCalibration, "Calibration 1\nCalibration 2\nCalibration 3");
    lv_obj_set_width(ui_ddSettingsCalibration, 150);
    lv_obj_set_height(ui_ddSettingsCalibration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddSettingsCalibration, -30);
    lv_obj_set_y(ui_ddSettingsCalibration, -124);
    lv_obj_set_align(ui_ddSettingsCalibration, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddSettingsCalibration, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ddSettingsTimeset = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_ddSettingsTimeset, "Timeset 1\nTimeset 2\nTimeset 3");
    lv_obj_set_width(ui_ddSettingsTimeset, 150);
    lv_obj_set_height(ui_ddSettingsTimeset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddSettingsTimeset, -30);
    lv_obj_set_y(ui_ddSettingsTimeset, -74);
    lv_obj_set_align(ui_ddSettingsTimeset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddSettingsTimeset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_btnSettingsCalEdit = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_btnSettingsCalEdit, 80);
    lv_obj_set_height(ui_btnSettingsCalEdit, 39);
    lv_obj_set_x(ui_btnSettingsCalEdit, 100);
    lv_obj_set_y(ui_btnSettingsCalEdit, -124);
    lv_obj_set_align(ui_btnSettingsCalEdit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingsCalEdit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSettingsCalEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSettingsCalEdit, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_btnSettingsCalEdit, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_lbBtnSettingsCalEdit = lv_label_create(ui_btnSettingsCalEdit);
    lv_obj_set_width(ui_lbBtnSettingsCalEdit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnSettingsCalEdit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnSettingsCalEdit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnSettingsCalEdit, "Edit");
    lv_obj_set_style_text_font(ui_lbBtnSettingsCalEdit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnSettingsWeb = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_pnSettingsWeb, 307);
    lv_obj_set_height(ui_pnSettingsWeb, 78);
    lv_obj_set_x(ui_pnSettingsWeb, 149);
    lv_obj_set_y(ui_pnSettingsWeb, 181);
    lv_obj_set_align(ui_pnSettingsWeb, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnSettingsWeb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnSettingsWeb, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnSettingsWeb, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPnSettingsWeb = lv_label_create(ui_pnSettingsWeb);
    lv_obj_set_width(ui_lbPnSettingsWeb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPnSettingsWeb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPnSettingsWeb, -80);
    lv_obj_set_y(ui_lbPnSettingsWeb, 0);
    lv_obj_set_align(ui_lbPnSettingsWeb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbPnSettingsWeb, "Web");
    lv_obj_set_style_text_font(ui_lbPnSettingsWeb, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnSettingsOthers = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_pnSettingsOthers, 420);
    lv_obj_set_height(ui_pnSettingsOthers, 110);
    lv_obj_set_x(ui_pnSettingsOthers, 0);
    lv_obj_set_y(ui_pnSettingsOthers, 20);
    lv_obj_set_align(ui_pnSettingsOthers, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnSettingsOthers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Settings_Slider1 = lv_slider_create(ui_pnSettingsOthers);
    lv_slider_set_value(ui_Settings_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Settings_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Settings_Slider1, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Settings_Slider1, 100);
    lv_obj_set_height(ui_Settings_Slider1, 10);
    lv_obj_set_x(ui_Settings_Slider1, -51);
    lv_obj_set_y(ui_Settings_Slider1, -34);
    lv_obj_set_align(ui_Settings_Slider1, LV_ALIGN_CENTER);

    ui_lbSettingsBrightness = lv_label_create(ui_pnSettingsOthers);
    lv_obj_set_width(ui_lbSettingsBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingsBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSettingsBrightness, -161);
    lv_obj_set_y(ui_lbSettingsBrightness, -35);
    lv_obj_set_align(ui_lbSettingsBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSettingsBrightness, "Brightness:");

    ui_lbSettingsBrightness1 = lv_label_create(ui_pnSettingsOthers);
    lv_obj_set_width(ui_lbSettingsBrightness1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingsBrightness1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSettingsBrightness1, 90);
    lv_obj_set_y(ui_lbSettingsBrightness1, -35);
    lv_obj_set_align(ui_lbSettingsBrightness1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSettingsBrightness1, "Dark theme:");

    ui_swSettingsDarkTheme = lv_switch_create(ui_pnSettingsOthers);
    lv_obj_set_width(ui_swSettingsDarkTheme, 50);
    lv_obj_set_height(ui_swSettingsDarkTheme, 25);
    lv_obj_set_x(ui_swSettingsDarkTheme, 173);
    lv_obj_set_y(ui_swSettingsDarkTheme, -35);
    lv_obj_set_align(ui_swSettingsDarkTheme, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_swSettingsDarkTheme, LV_STATE_CHECKED);       /// States

    ui_lbSettingsBuzzer = lv_label_create(ui_pnSettingsOthers);
    lv_obj_set_width(ui_lbSettingsBuzzer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingsBuzzer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSettingsBuzzer, 108);
    lv_obj_set_y(ui_lbSettingsBuzzer, -4);
    lv_obj_set_align(ui_lbSettingsBuzzer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSettingsBuzzer, "Buzzer:");

    ui_swSettingsDarkTheme1 = lv_switch_create(ui_pnSettingsOthers);
    lv_obj_set_width(ui_swSettingsDarkTheme1, 50);
    lv_obj_set_height(ui_swSettingsDarkTheme1, 25);
    lv_obj_set_x(ui_swSettingsDarkTheme1, 173);
    lv_obj_set_y(ui_swSettingsDarkTheme1, -3);
    lv_obj_set_align(ui_swSettingsDarkTheme1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_swSettingsDarkTheme1, LV_STATE_CHECKED);       /// States

    ui_ddSettingsLanguage = lv_dropdown_create(ui_pnSettingsOthers);
    lv_dropdown_set_options(ui_ddSettingsLanguage, "English");
    lv_obj_set_width(ui_ddSettingsLanguage, 150);
    lv_obj_set_height(ui_ddSettingsLanguage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddSettingsLanguage, -38);
    lv_obj_set_y(ui_ddSettingsLanguage, 2);
    lv_obj_set_align(ui_ddSettingsLanguage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddSettingsLanguage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_lbSettingsBrightness3 = lv_label_create(ui_pnSettingsOthers);
    lv_obj_set_width(ui_lbSettingsBrightness3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingsBrightness3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSettingsBrightness3, -157);
    lv_obj_set_y(ui_lbSettingsBrightness3, 1);
    lv_obj_set_align(ui_lbSettingsBrightness3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSettingsBrightness3, "Language:");

    lv_obj_add_event_cb(ui_pnSettingsSave, ui_event_pnSettingsSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddSettingsCalibration, ui_event_ddSettingsCalibration, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddSettingsTimeset, ui_event_ddSettingsTimeset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSettingsCalEdit, ui_event_btnSettingsCalEdit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnSettingsWeb, ui_event_pnSettingsWeb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swSettingsDarkTheme, ui_event_swSettingsDarkTheme, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_pnSettingsSave = NULL;
    ui_lbPnSettingsSave = NULL;
    ui_lbSettingsCal = NULL;
    ui_lbSettingsTimeset = NULL;
    ui_ddSettingsCalibration = NULL;
    ui_ddSettingsTimeset = NULL;
    ui_btnSettingsCalEdit = NULL;
    ui_lbBtnSettingsCalEdit = NULL;
    ui_pnSettingsWeb = NULL;
    ui_lbPnSettingsWeb = NULL;
    ui_pnSettingsOthers = NULL;
    ui_Settings_Slider1 = NULL;
    ui_lbSettingsBrightness = NULL;
    ui_lbSettingsBrightness1 = NULL;
    ui_swSettingsDarkTheme = NULL;
    ui_lbSettingsBuzzer = NULL;
    ui_swSettingsDarkTheme1 = NULL;
    ui_ddSettingsLanguage = NULL;
    ui_lbSettingsBrightness3 = NULL;

}
