// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Zolar2

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern void ui_event_pnSettingsSave(lv_event_t * e);
extern lv_obj_t * ui_pnSettingsSave;
extern lv_obj_t * ui_lbPnSettingsSave;
extern lv_obj_t * ui_lbSettingsCal;
extern lv_obj_t * ui_lbSettingsTimeset;
extern void ui_event_ddSettingsCalibration(lv_event_t * e);
extern lv_obj_t * ui_ddSettingsCalibration;
extern void ui_event_ddSettingsTimeset(lv_event_t * e);
extern lv_obj_t * ui_ddSettingsTimeset;
extern void ui_event_btnSettingsCalEdit(lv_event_t * e);
extern lv_obj_t * ui_btnSettingsCalEdit;
extern lv_obj_t * ui_lbBtnSettingsCalEdit;
extern void ui_event_pnSettingsWeb(lv_event_t * e);
extern lv_obj_t * ui_pnSettingsWeb;
extern lv_obj_t * ui_lbPnSettingsWeb;
extern lv_obj_t * ui_pnSettingsOthers;
extern lv_obj_t * ui_Settings_Slider1;
extern lv_obj_t * ui_lbSettingsBrightness;
extern lv_obj_t * ui_lbSettingsBrightness1;
extern void ui_event_swSettingsDarkTheme(lv_event_t * e);
extern lv_obj_t * ui_swSettingsDarkTheme;
extern lv_obj_t * ui_lbSettingsBuzzer;
extern lv_obj_t * ui_swSettingsDarkTheme1;
extern lv_obj_t * ui_ddSettingsLanguage;
extern lv_obj_t * ui_lbSettingsBrightness3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

